create login signup dashboard home about pages and create user redux
ahsanreal4/Blog-App pull request #1
Opened 2024-10-03 12:51 UTC by Faizan707

2024-10-03 12:53 UTC, Faizan707 reviewed
sir please review

2024-10-03 13:13 UTC, ahsanreal4 commented on frontend/src/App.js
Create these routes in a seperate file and then import here.

2024-10-03 13:30 UTC, ahsanreal4 requested changes

2024-10-03 13:30 UTC, ahsanreal4 commented on frontend/src/App.js
Also create a pages.js file and save all Routes there like
const PAGES = [
HOME : "/",
ABOUT_US: "/about-us",
LOGIN: "/login"
}
This will ensure consistency of routes all over the app

2024-10-03 13:30 UTC, ahsanreal4 commented on frontend/src/App.js
Use routes every where from this file if you want Home route use PAGES.HOME

2024-10-03 13:30 UTC, ahsanreal4 commented on frontend/src/components/Navbar.jsx
Create an array of objects for Navbar headings like
const HEADINGS = [ 
{name: "Home", link: PAGES.HOME},
{name: "About Us", link: PAGES.ABOUT_US
];

then map this list for both desktop and mobile versions of your navbar code.
example:-
{HEADINGS.map((heading) => 
< Link key={heading.name} to={heading.link}>{heading.name}< /Link>)
}

2024-10-03 13:30 UTC, ahsanreal4 commented on frontend/src/pages/Dashboard.jsx
- create a function to get storage token like getAuthToken() instead of calling localStorage.getItem everywhere
- create axios instance so you don't have to pass Authorization header and base url again and again. Create a function that returns the axios instace like getAxiosInstance(). Make this change everywhere you called api in the app.
- use hooks to call api like useGetUser() and useSignUpUser().
Read the docs: https://axios-http.com/docs/instance

2024-10-03 13:31 UTC, ahsanreal4 commented
> sir please review

Done

2024-10-03 13:31 UTC, ahsanreal4 commented
> sir please review

Done

2024-10-04 04:32 UTC, Faizan707 commented on frontend/src/App.js
done sir happy

2024-10-04 05:18 UTC, ahsanreal4 requested changes

2024-10-04 05:18 UTC, ahsanreal4 commented on frontend/src/App.js
read first comment. I told you to also create these routes in a seperate file and then import them here.

2024-10-04 05:18 UTC, ahsanreal4 commented on frontend/src/components/ProtectedRoutes.jsx
ProtectedRoutes file should not be in components folder. 
It should be in seperate routes folder.

2024-10-04 05:18 UTC, ahsanreal4 commented on frontend/src/pages/Dashboard.jsx
this one still not fixed

2024-10-04 05:37 UTC, Faizan707 commented on frontend/src/App.js
done sir

2024-10-04 05:38 UTC, Faizan707 commented on frontend/src/components/ProtectedRoutes.jsx
ok

2024-10-04 05:43 UTC, Faizan707 commented on frontend/src/pages/Dashboard.jsx
fixing sir give me time i am not as fast as you

2024-10-04 06:36 UTC, ahsanreal4 requested changes

2024-10-04 06:36 UTC, ahsanreal4 commented on frontend/src/pages/Dashboard.jsx
getAuthToken should be created in seperate file named in utils/auth.js and exported for use all over the app.
Other than that use this axios instance and custom hooks for all api calls in the app in Signup and Login page too.

2024-10-04 06:36 UTC, ahsanreal4 commented on frontend/src/hooks/useLogin.jsx
Axios instance hi nai use kr rha chutiya ghr le kr jana hai ose.

- You don't need to check response.status == 200  for request. if the request fails it will automatically go to catch block.
- Use axios instance for your api calls.
- Create setAuthToken function in utils/auth.js file that takes token as parameter setAuthToken(token) and sets it to local storage
- Also make hook for Dashboard api.

2024-10-04 09:41 UTC, ahsanreal4 requested changes
Its a lot better. But useSignUp and Dashboard api custom hook is missing.

2024-10-04 09:56 UTC, ahsanreal4 requested changes

2024-10-04 09:56 UTC, ahsanreal4 commented on frontend/src/hooks/useFetchUsers.jsx
> +  }, [dispatch]);
useEffect dependency array se dispatch remove

2024-10-04 10:03 UTC, ahsanreal4 approved these changes

2024-10-04 10:03 UTC, merged